language: ruby
rvm:
- 2.0.0
script: bundle exec rake build
before_install:
 - sudo apt-get update
 - sudo apt-get install imagemagick
install: bundle install
after_success: bundle exec s3_website push --headless
env:
  global:
  - secure: d0EIHVzl5FdpyBBAmkhw5Y6777ZFltNTX6GTF4LH7h5Q3hVNcvCN+rrjTa5jggBOI3877w0up+u4Os0JNxhVkDuUZzyfTNFhy/XGyH0daXnokHv5PR3aKIx5ezmyj0lm6fRh7/sXZ40qLwk3Kye6Y7S6Nxs/DC/5sOuL9PaPjkc=
  - secure: MUnYfGidHxfjO/aZgASAz7aMTDg2LxAM9HnS8fjy2kKzay8Tu83yUY8mr3tKfOugVSzznRDthLdRW0ZLy2SurQbm8YcsatRNBFsogkAPkZLMPGaqxbrIvyi7bYpru5KtFfJIMSS3GPct0Q1FN/d6yssQsvWwLTSaGMMoO0RjzG0=
