name: "KBM"
description: "KBM Main Website"

url: "[localhost:4001]"
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

permalink: pretty

sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed
