name: "KBM"
description: "Kingdom Building Ministries"
future: false

exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

permalink: pretty

sass:
  style: expanded
  deploy_style: compressed

markdown: redcarpet
redcarpet:
  extensions: [tables, lax_spacing, smart]