name: "KBM"
description: "KBM Main Website"

url: "[localhost:4001]"
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
include:
  - _*.scss
permalink: pretty

sass:
    syntax: scss        # scss|sass
    style:  expanded  # nested|expanded|compact|compressed
