name: "Kingdom Building Ministries"
description: "Kingdom Building Ministries"
future: false
siteurl: http://www.kbm.org

relative_permalinks: false
timezone: 'America/Denver'

exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

permalink: pretty

# search index limited to only blog posts right now
lunr_search:
  excludes: ["^(?!\\/blog/).+"]

sass:
  style: expanded
  deploy_style: compressed

markdown: redcarpet
redcarpet:
  extensions: [tables, lax_spacing, smart]
