name: "KBM"
description: "KBM Main Website"

url: "[localhost:4000]"
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

permalink: pretty

sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed

navigation:
  - text: About Us
    url: /about
    id: about-menu
    items:
      - text: About Pages
        url: /about
  - text: Speakers
    url: /
    id: speakers-menu
  - text: Training
    url: /travel.html
    id: training-menu
  - text: Fuel
    url: /travel.html
    id: fuel-menu
  - text: Get Involved
    url: /travel.html
    id: get-involved-menu
  - text: Store
    url: /travel.html
    id: store-menu
    